### ISSUE TITLE
Need memory usage comparison with standard map

### ISSUE THREAD

**Issue by kokizzu** [openacid/slim#105]
so people know what's benefit this library provide compared to map other than ordered data.

**Comment by drmingdrmer** [comment]
Thanks for the reminding 😃😃 

Yes, previously I did have a memory usage comparison chart but it seems misleading because people thought SlimTrie provides exactly the same functionality as map does.
But actually, it is not. 

Thus I decided to make a benchmark with a more precise scenario description.
But before I had time for this. I prefer not to give this piece of misleading information.

If you are interested, there is still some stat here: `docs/trie/memusage.md`.
